import os
from pypdf import PdfReader

MAX_PAGES = 150
MAX_FILE_SIZE_MB = 50
MIN_CHARS_PER_PAGE = 100


def check_file_limits(file_path):
    """
    Checks file size and page count before attempting extraction.
    Returns (ok: bool, error_message: str or None)
    """
    size_mb = os.path.getsize(file_path) / (1024 * 1024)
    if size_mb > MAX_FILE_SIZE_MB:
        return False, f"File too large ({size_mb:.1f}MB). Maximum supported size is {MAX_FILE_SIZE_MB}MB."

    try:
        reader = PdfReader(file_path)
        page_count = len(reader.pages)
        if page_count > MAX_PAGES:
            return False, f"PDF too long ({page_count} pages). Maximum supported length is {MAX_PAGES} pages."
    except Exception as e:
        return False, f"Could not read PDF: {e}"

    return True, None


def detect_scanned_pdf(text, page_count):
    """
    Heuristic: if average extracted text per page is very low,
    the PDF is likely scanned/image-based rather than digital text.
    Returns (is_scanned: bool, warning_message: str or None)
    """
    if page_count == 0:
        return True, "No pages found in PDF."

    chars_per_page = len(text) / page_count
    if chars_per_page < MIN_CHARS_PER_PAGE:
        return True, (
            f"Very little text extracted ({chars_per_page:.0f} chars/page average). "
            f"This PDF appears to be scanned or image-based — "
            f"text extraction is not supported yet."
        )
    return False, None


def extract_text(file_path):
    """
    Extracts all text from a PDF and returns it as a single string.
    Checks file limits, detects scanned PDFs, and collapses
    double-spaces caused by character-level PDF positioning.
    Returns None if the file can't be read or fails validation.
    """
    ok, error = check_file_limits(file_path)
    if not ok:
        print(f"[parse.py] File rejected: {error}")
        return None

    try:
        reader = PdfReader(file_path)
    except Exception as e:
        print(f"[parse.py] Could not open PDF: {e}")
        return None

    full_text = []
    for page_num, page in enumerate(reader.pages):
        try:
            text = page.extract_text()
            if text:
                full_text.append(text)
            else:
                print(f"[parse.py] No extractable text on page {page_num + 1} (possibly scanned/image-only)")
        except Exception as e:
            print(f"[parse.py] Failed to extract text from page {page_num + 1}: {e}")

    result = "\n".join(full_text)

    # collapse multiple spaces caused by character-level PDF positioning
    # (common in PDFs generated by certain tools where each character
    # is positioned individually rather than as a word/line unit)
    result = " ".join(result.split())

    # detect scanned PDF after extraction
    page_count = len(reader.pages)
    is_scanned, warning = detect_scanned_pdf(result, page_count)
    if is_scanned:
        print(f"[parse.py] Warning: {warning}")
        return None

    return result


if __name__ == "__main__":
    import sys
    test_path = sys.argv[1] if len(sys.argv) > 1 else "data/testpdf.pdf"
    result = extract_text(test_path)
    if result:
        print(f"Extracted {len(result)} characters.")
        print(f"Preview:\n{result[:500]}")
    else:
        print("No text extracted.")